apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql
  name: mysql-storage-pvc-new
  annotations:
     volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-containter
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: rootpwd
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-storage-vol-new
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage-vol-new
        persistentVolumeClaim:
          claimName: mysql-storage-pvc-new
