apiVersion: v1
kind: Service
metadata:
  labels:
    app: limesurvey
    tiers: frontend
  name: limesurvey
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: limesurvey
    tiers: frontend
  type: LoadBalancer
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  labels:
#    app: limesurvey
#  name: limesurvey-upload
#spec:
#  accessModes:
#  - ReadWriteMany
#  resources:
#    requests:
#      storage: 5Gi
#  selector:
#    matchLabels:
#      app: limesurvey
#      tiers: frontend
#status: {}
#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: limesurvey
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: limesurvey
        tiers: frontend
    spec:
      containers:
      - name: limesurvey
        image: crramirez/limesurvey:latest
        env: 
        - name: DISABLE_MYSQL
          value: 'yes'
        ports:
        - containerPort: 80
          name: http
       # volumeMounts:
       # - mountPath: /var/www/html/upload
       #   name: limesurvey-upload
       #   subPath: limesurvey-upload
        livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
        readinessProbe:
            tcpSocket:
              port: 80
            timeoutSeconds: 5
      #volumes:
      #- name: limesurvey-upload
      #  persistentVolumeClaim:
      #    claimName: limesurvey-upload
status: {}
