apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-svc
spec:
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: bXlzcWxyb290cHdk
  #senha em claro é: mysqlrootpwd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-containter
        args:
          - "--ignore-db-dir=lost+found"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: root-password
        ports:
        - containerPort: 3306
          name: mysql-port    
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-storage-vol
      volumes:
        - name: mysql-storage-vol
          persistentVolumeClaim:
            claimName: mysql-storage-pvc
status: {}
