apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: limesurvey
  name: limesurvey-upload
  annotations:
     volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}